name: pipeline
on:
  push:
    branches:
      - main

jobs:
  test:
    name: test code
    runs-on: ubuntu-latest
    env:
      BUCKET_HOST: none
      DB_ADMIN_USER: root
      DB_ADMIN_PASSWORD: 1234
      DB_HOST: database
      DB_NAME: therapisttrack
      DB_USER: adminstrator
      DB_USER_PASSWORD: 1234
      DB_PORT: 27017
      DELAY_START: 8000

      API_PORT: 3001
      JWT_SECRET: 'LocalPassword'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start containers
        run: docker compose -f "compose.test.yaml" up -d --build

      - name: owo
        run: |
          while ! curl -s http://localhost:3001 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done

      - name: Stop containers
        if: always()
        run: docker compose -f "compose.test.yaml" down -v
